# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160311_1241'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prices',
            field=models.ManyToManyField(to='products.Product_price'),
        ),
    ]
