# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prices',
        ),
    ]
